language: go

go:
  - 1.11

services:
  - docker

before_script:
  - docker-compose -f tests/integration/docker-compose.yml up -d --build

after_script:
  - docker-compose -f tests/integration/docker-compose.yml down

gobuild_args: -v -tags=integration
